### ISSUE TITLE
Put Summary at the top of the report

### ISSUE THREAD

**Issue by Sarkie** [mgm3746/garbagecat#200]
Put Summary at the top of the report

Not sure I need to see the gc log at all, unless you have issues with a line, I have the gc log already, I just need the summary

**Comment by mgm3746** [comment]
I can move the summary to the top. It's not showing the complete gc.log. It's showing gc logging lines where the throughput is less than some value (default 90%). I generally set it to 20% with the "-t 20" option. It's critical information because the max pause can be low and the overall throughput great, and there is some 2 minute block when there was one gc after another trying to free space. I call that "localized throughput".

**Comment by mgm3746** [comment]
Please take a look at the change, and let me know what you think.

**Comment by mgm3746** [comment]
If this is not resolved to your satisfaction, please re-open.
