### ISSUE TITLE
*Undefined JVM option(s): -XX:+FlightRecorder -XX:+UnlockCommercialFeatures.

### ISSUE THREAD

**Issue by Sarkie** [mgm3746/garbagecat#201]
*Undefined JVM option(s): -XX:+FlightRecorder -XX:+UnlockCommercialFeatures.

**Comment by mgm3746** [comment]
Hi, it looks like you are using the 4.0.1 release, as -XX:+FlightRecorder is a recognized option in the main branch.

I have added -XX:+UnlockCommercialFeatures.

I recommend using the garbagecat image, not the published release:
$ docker run --pull=always -v "$PWD":/home/garbagecat/files:z ghcr.io/mgm3746/garbagecat:main -t 20 -p -c /home/garbagecat/files/gc.log > gc.log.cat

Run that command in the directory where gc.log exists, and it will create the report as gc.log.cat.

The reason to use the container is because the image is automatically rebuilt whenever there is a commit, so you always have the latest release.

Please test the container build and confirm this is now fixed.

**Comment by mgm3746** [comment]
Fixed in latest release.
