### ISSUE TITLE
Is the release on github not updated for a long time?

### ISSUE THREAD

**Issue by youngledo** [mgm3746/garbagecat#211]
<img width="601" alt="image" src="https://github.com/user-attachments/assets/dcac6b87-451e-44b3-b5ca-3e474d1d1e1b">
This is still from March last year.

**Comment by mgm3746** [comment]
Hi,

The image is updated with every checkin, so I was thinking there is not much demand for a regular build, due to these continuous builds.

Are you able to run the image using podman/docker? 

For example, run the following in the directory where gc.log exists:
$ docker run --pull=always -v "$PWD":/home/garbagecat/files:z ghcr.io/mgm3746/garbagecat:main -t 20 -p -c /home/garbagecat/files/gc.log > gc.log.cat

Or,  is this not possible for some reason, and you still find the jar build useful?

Thank you,
Mike

**Comment by mgm3746** [comment]
I pushed out a new release.

**Comment by mgm3746** [comment]
Going forward, I will test not do any more jar releases. I will do a few "dummy" releases, where there will be no assets and just instructions how to run the container. Anyone needing to run a jar would have to check out the code and build it. I will close this, but please comment to re-open if you see some issue with that.
