### ISSUE TITLE
PrintGCApplicationStoppedTime is not detected in log

### ISSUE THREAD

**Issue by bostrt** [mgm3746/garbagecat#55]
I have a sample file where `PrintGCApplicationStoppedTime` is enabled but garbagecat is not detecting it. Example gc log is here: [test.txt](https://github.com/mgm3746/garbagecat/files/579229/test.txt)

**Comment by mgm3746** [comment]
I tested and it parses. You have to preprocess because it has datestamps. Like this:
java -jar garbagecat-2.0.5.jar -p -t 50 ~/tmp/test.txt

None of the logging events will recognize datestamps. During preprocessing all datestamps are converted to timestamps (e.g. 2016-11-02T03:45:31.166-0700: 9.289 --> 9.289). It was easier to do that than rework every regex when datestamps were added. 

Just about every logging requires preparsing now. It probably should be a default option at this point.

Anyway, update w/ the latest and test again, and it should work now w/ preprocessing enabled.
